### ISSUE TITLE
Revision de TP_1

### ISSUE THREAD

**Issue by jesicaporporato-SSL-Grupo1** [jesicaporporato-SSL-Grupo1/2020_K2001_Grupo_1#1]
Hola, ya subimos el TP_1 .
@santiagoferreiros 

Gracias.

**Comment by santiagoferreiros** [comment]
Estimado grupo !

Excelente trabajo, hay algunos printf que quedaron demás, y salen algunas cosas por la salida de la consulta innecesaria. Después por favor, comentar esos printf.

La última constante que reconoce el archivo queda con un salto de línea adicional. Revisar!

Nota: 9
Excelente ! 

@jesicaporporato-SSL-Grupo1 
@MariaDelCarmenLuque
@Rodrigocc12 
@Lucassiturrioz 

FALTA ALGUIEN EN EL REPOSITORIO. Por favor, agregar y trabajar todos.

Saludos :)
